# To do 
The submission scoring is not working properly. Order of checking
1) Submit the data without the model prediction or appending datasets - WORKED - 5.465

2) Submit the data with model prediction, without appending datasets - WORKED - 5.6189

3) Submit the data with model prediciton, appending datasets, but no retraining of the model - 5.6189

4) Submit the data with model prediction and retraining, 2 days in the past - ERROR (there might have been a training error with appending of the datasets.

5) Submit the data with model prediction and retraining (different ratraining procedures), decreasing the size of the main dataset - 2 days in the past -  5.6075

---------------------------------------------

6) Use the full dataset each iteration for retraining, only fit (to test the load) - 5.4165

7) Use the full dataset after each iteration, try new model each time for retraining,not only fit,but full train (to test the load)

## Proper test selection, so it mimicks the real data
## Do the evaluation and validation for hyperparameters
## Think about multiple vs single stock models

## I am only retraining after a full day, but test data is available every 10 seconds

https://www.kaggle.com/code/robikscube/pt2-time-series-forecasting-with-xgboost/notebook

https://www.youtube.com/watch?v=z3ZnOW-S550&t=869s

https://www.youtube.com/watch?v=GrJP9FLV3FE

# Hyperparameter

In [3]:
import pandas as pd
models = ['all_stocks_xgboost_daily_retraining_on_daily_data_n_folds_2.csv']
hyper_dict = {}
for n_folds in [5]:
    hyper_dict[n_folds] = {}
    for m_i, model in enumerate(models):
        hyperparameter_results = pd.read_csv(model +'_'+ str(n_folds) +'.csv',index_col =[0])
        hyperparameter_results = hyperparameter_results.sort_values(['test_mean_mae'], ascending=[True]).round(4)
        hyper_dict[n_folds][m_i] = hyperparameter_results.copy()
        #for parameter in hyperparameter_results.columns[:-3]:
        #     hyper_dict[n_folds][m_i][parameter] = hyperparameter_results .groupby([parameter])[['mean_mae','std_mae','daily_var_mean']].mean().copy()

FileNotFoundError: [Errno 2] No such file or directory: 'all_stocks_xgboost_daily_retraining_on_full_data_n_folds_5.csv'

In [4]:
hyper_dict[5][0]

KeyError: 0

In [5]:
hyper_dict[5][1]

KeyError: 1

In [231]:
hyperparameter_results_dict = {}
for parameter in hyperparameter_results.columns[:-3]:
    print(parameter)
    hyperparameter_results_dict[parameter] = hyperparameter_results .groupby([parameter])[['mean_mae','std_mae','daily_var_mean']].mean()

max_depth

KeyError: "Columns not found: 'daily_var_mean', 'std_mae', 'mean_mae'"

In [225]:
hyper_dict[3][0] - hyper_dict[3][1]

   max_depth  n_estimator  mean_mae   std_mae  daily_var_mean
0          0            0 -1.843120 -0.009846       -0.037305
1          0            0 -3.283711 -0.199195        0.030747
2          0            0 -1.984654 -0.024089        0.166188
3          0            0 -1.679700  1.143647        0.218722

In [226]:
hyper_dict[5][0] - hyper_dict[5][1]

   max_depth  n_estimator  mean_mae   std_mae  daily_var_mean
0          0            0 -1.192884 -0.255662       -0.053009
1          0            0 -2.498346  0.108769       -0.028465
2          0            0 -2.184049 -0.149826       -0.067908
3          0            0 -2.856737  0.162640       -0.010745

In [228]:
hyper_dict[5][0]

   max_depth  n_estimator  mean_mae   std_mae  daily_var_mean
0          3           50  6.929428  0.708844        0.145047
1          7           50  8.351217  0.917039        0.206292
2          3          150  7.142979  0.714317        0.159069
3          7          150  9.447786  1.060653        0.255627

In [227]:
hyper_dict[3][0]

   max_depth  n_estimator   mean_mae   std_mae  daily_var_mean
0          3           50   6.858411  0.762255        0.138477
1          7           50   8.850907  1.124012        0.276783
2          3          150   8.160123  1.144733        0.364476
3          7          150  12.955450  2.882575        0.511751

In [117]:
import pandas as pd
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import xgboost as xgb
import time
import matplotlib.pyplot as plt
print("Loading data")
dtypes = {
    'stock_id' : np.uint8,
    'date_id' : np.uint16,
    'seconds_in_bucket' : np.uint16,
    'imbalance_buy_sell_flag' : np.int8,
    'time_id' : np.uint16,
}
df = pd.read_csv('train.csv', dtype = dtypes).drop(['row_id','time_id'], axis = 1)

df['far_price'] = df.apply(
    lambda row: -1 if np.isnan(row['far_price']) else row['far_price'],
    axis=1)

df['near_price'] = df.apply(
    lambda row: -1 if np.isnan(row['near_price']) else row['near_price'],
    axis=1)
df = df.dropna()
X_entire_dataset, y_entire_dataset = df.iloc[:,:-1].copy(),df.iloc[:,-1].copy()
x_columns = X_entire_dataset.columns

print("Creating folds")
number_of_stocks = 200
number_of_bucket_iter = 55
model_name = 'all_stocks_xgboost'
retraining_freq = 'daily_retraining'
retraining_method = 'on_full_data'
# Creating time series folds
fold_dict = {}
X_train_dict = {}
y_train_dict = {}
X_test_dict = {}
y_test_dict = {}
number_of_folds = 5
total_number_of_days = 480
fold_size =  total_number_of_days/number_of_folds
rolling_test_size_ratio

Loading data
Creating folds

TypeError: create_folds() missing 1 required positional argument: 'df'

In [193]:
rolling_test_size_ratio = 10
def create_folds(number_of_folds,rolling_test_size_ratio,df):
    rolling_test_size = fold_size//rolling_test_size_ratio
    print("Creating",number_of_folds,'folds')
    fold_dict = {}
    X_train_dict = {}
    y_train_dict = {}
    X_test_dict = {}
    y_test_dict = {}
    for f_i in range(1,number_of_folds+1):
        train_start_date = (f_i-1) * fold_size
        train_end_date = f_i * fold_size - rolling_test_size
        test_start_date = f_i * fold_size - rolling_test_size
        test_end_date =  f_i * fold_size
        
        fold = df.loc[(df['date_id'] < test_end_date)& (df['date_id']  >= train_start_date)]
        X_train = df.loc[(df['date_id'] < train_end_date)& (df['date_id']  >= train_start_date)][x_columns]
        y_train = df.loc[(df['date_id'] < train_end_date)& (df['date_id']  >= train_start_date)][['target']]
        
        X_test =  df.loc[(df['date_id'] < test_end_date)& (df['date_id']  >=  test_start_date )][x_columns]
        y_test = df.loc[(df['date_id'] < test_end_date)& (df['date_id']   >=  test_start_date )][['target']]
        if f_i == number_of_folds:
            fold = df.loc[(df['date_id'] <= test_end_date)& (df['date_id']  >= train_start_date)]
            X_test =  df.loc[(df['date_id'] <= test_end_date)& (df['date_id']  >=  test_start_date )][x_columns]
            y_test = df.loc[(df['date_id'] <= test_end_date)& (df['date_id']   >=  test_start_date )][['target']]
        fold_dict[f_i] = fold.copy()
        
        X_train_dict[f_i] =  X_train.copy()
        y_train_dict[f_i] =  y_train.copy()
        
        X_test_dict[f_i] =  X_test.copy()
        y_test_dict[f_i] =  y_test.copy()
    return fold_dict,X_train_dict, y_train_dict,X_test_dict, y_test_dict
fold_dict,X_train_dict, y_train_dict,X_test_dict, y_test_dict = create_folds(number_of_folds,rolling_test_size_ratio,df)

Creating 5 folds

In [198]:

start = time.time()
result_fold_list = []
result_fold_variance_mean_list = []
for f_i in range(1,6):
    start_fold = time.time()
    # Model is pretrained with the training data
    model = xgb.XGBRegressor(base_score=0.5, booster='gbtree',    
               n_estimators=n_estimator,
               objective='reg:squarederror',
               max_depth=max_depth,
               eta=0.3,
                min_child_weight=0,
                subsample =1,
                gamma =0)

   # model.fit(X_test_dict[f_i], y_test_dict[f_i])
    daily_result_list = []
    for date_id in sorted(X_test_dict[f_i]['date_id'].unique()):
        # Retraining the model with previous day data
        test_start_date_id =  min(X_test_dict[f_i]['date_id'].unique())
        if date_id > test_start_date_id:
            X_previous_day_test = X_test_dict[f_i][X_test_dict[f_i]['date_id'] == date_id - 1].copy()
            y_previous_day_test =  y_test_dict[f_i][X_test_dict[f_i]['date_id'] == date_id - 1].copy()
            X_train_dict[f_i] = pd.concat([X_train_dict[f_i],X_previous_day_test ])
            y_train_dict[f_i] = pd.concat([y_train_dict[f_i],y_previous_day_test])
            #model.fit(X_previous_day_test , y_previous_day_test,xgb_model=booster)
            print(max(X_train_dict[f_i] ['date_id'].value_counts()))
            #model.fit(X_test_dict[f_i] , y_test_dict[f_i],xgb_model =  model.get_booster())
        #Predicting the current day data
        X_current_test = X_test_dict[f_i][X_test_dict[f_i]['date_id'] == date_id].copy()
        y_current_test = y_test_dict[f_i][X_test_dict[f_i]['date_id'] == date_id].copy()
        #y_predict = model.predict(X_current_test[X_current_test['date_id'] == date_id])
        #result_daily = mean_absolute_error(y_predict , y_current_test)
        #daily_result_list.append(result_daily)
        end_fold = time.time()
        print('Validation',count,'out of',total_iter,'| Fold:',f_i,'out of',number_of_folds,'| Date:',date_id,'from',min( X_test_dict[f_i]['date_id'].unique()),'to', max(X_test_dict[f_i]['date_id'].unique()),'| Total time spent on this fold',np.round((end_fold - start_fold)/60,2),'minutes ****')

    result_fold = np.mean( daily_result_list)
    result_fold_list.append(result_fold)

    result_fold_daily_variance = np.std( daily_result_list)/np.mean( daily_result_list)
    result_fold_variance_mean_list.append(result_fold_daily_variance)

Validation 1 out of 16 | Fold: 1 out of 5 | Date: 87 from 87 to 95 | Total time spent on this fold 0.0 minutes ****
21560
Validation 1 out of 16 | Fold: 1 out of 5 | Date: 88 from 87 to 95 | Total time spent on this fold 0.0 minutes ****
21670
Validation 1 out of 16 | Fold: 1 out of 5 | Date: 89 from 87 to 95 | Total time spent on this fold 0.0 minutes ****
21670
Validation 1 out of 16 | Fold: 1 out of 5 | Date: 90 from 87 to 95 | Total time spent on this fold 0.0 minutes ****
21670
Validation 1 out of 16 | Fold: 1 out of 5 | Date: 91 from 87 to 95 | Total time spent on this fold 0.01 minutes ****
21670
Validation 1 out of 16 | Fold: 1 out of 5 | Date: 92 from 87 to 95 | Total time spent on this fold 0.01 minutes ****
21670
Validation 1 out of 16 | Fold: 1 out of 5 | Date: 93 from 87 to 95 | Total time spent on this fold 0.01 minutes ****
21670
Validation 1 out of 16 | Fold: 1 out of 5 | Date: 94 from 87 to 95 | Total time spent on this fold 0.01 minutes ****
21670
Validation 1 out of 16 | Fold: 1 out of 5 | Date: 95 from 87 to 95 | Total time spent on this fold 0.01 minutes ****
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 183 from 183 to 191 | Total time spent on this fold 0.0 minutes ****

/mnt/sdb1/luk/anaconda2021/envs/gt/lib/python3.9/site-packages/numpy/core/fromnumeric.py:3440: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/mnt/sdb1/luk/anaconda2021/envs/gt/lib/python3.9/site-packages/numpy/core/_methods.py:189: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/mnt/sdb1/luk/anaconda2021/envs/gt/lib/python3.9/site-packages/numpy/core/_methods.py:262: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/mnt/sdb1/luk/anaconda2021/envs/gt/lib/python3.9/site-packages/numpy/core/_methods.py:222: RuntimeWarning: invalid value encountered in true_divide
  arrmean = um.true_divide(arrmean, div, out=arrmean, casting='unsafe',
/mnt/sdb1/luk/anaconda2021/envs/gt/lib/python3.9/site-packages/numpy/core/_methods.py:254: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

21780
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 184 from 183 to 191 | Total time spent on this fold 0.0 minutes ****
21780
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 185 from 183 to 191 | Total time spent on this fold 0.0 minutes ****
21780
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 186 from 183 to 191 | Total time spent on this fold 0.0 minutes ****
21780
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 187 from 183 to 191 | Total time spent on this fold 0.01 minutes ****
21780
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 188 from 183 to 191 | Total time spent on this fold 0.01 minutes ****
21780
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 189 from 183 to 191 | Total time spent on this fold 0.01 minutes ****
21780
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 190 from 183 to 191 | Total time spent on this fold 0.01 minutes ****
21780
Validation 1 out of 16 | Fold: 2 out of 5 | Date: 191 from 183 to 191 | Total time spent on this fold 0.01 minutes ****
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 279 from 279 to 287 | Total time spent on this fold 0.0 minutes ****
10945
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 280 from 279 to 287 | Total time spent on this fold 0.0 minutes ****
10945
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 281 from 279 to 287 | Total time spent on this fold 0.0 minutes ****
10945
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 282 from 279 to 287 | Total time spent on this fold 0.01 minutes ****
10945
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 283 from 279 to 287 | Total time spent on this fold 0.01 minutes ****
10945
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 284 from 279 to 287 | Total time spent on this fold 0.01 minutes ****
10945
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 285 from 279 to 287 | Total time spent on this fold 0.01 minutes ****
10945
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 286 from 279 to 287 | Total time spent on this fold 0.01 minutes ****
10945
Validation 1 out of 16 | Fold: 3 out of 5 | Date: 287 from 279 to 287 | Total time spent on this fold 0.01 minutes ****
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 375 from 375 to 383 | Total time spent on this fold 0.0 minutes ****
11000
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 376 from 375 to 383 | Total time spent on this fold 0.0 minutes ****
11000
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 377 from 375 to 383 | Total time spent on this fold 0.0 minutes ****
11000
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 378 from 375 to 383 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 379 from 375 to 383 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 380 from 375 to 383 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 381 from 375 to 383 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 382 from 375 to 383 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 4 out of 5 | Date: 383 from 375 to 383 | Total time spent on this fold 0.01 minutes ****
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 471 from 471 to 480 | Total time spent on this fold 0.0 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 472 from 471 to 480 | Total time spent on this fold 0.0 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 473 from 471 to 480 | Total time spent on this fold 0.0 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 474 from 471 to 480 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 475 from 471 to 480 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 476 from 471 to 480 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 477 from 471 to 480 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 478 from 471 to 480 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 479 from 471 to 480 | Total time spent on this fold 0.01 minutes ****
11000
Validation 1 out of 16 | Fold: 5 out of 5 | Date: 480 from 471 to 480 | Total time spent on this fold 0.01 minutes ****

In [6]:
import pandas as pd
hyperparameters_df = pd.read_csv('all_stocks_xgboost_daily_retraining_on_daily_data_n_folds_2.csv',index_col=[0])
hyperparameters_df = hyperparameters_df.sort_values(['test_mean_mae'], ascending=[True]).round(4)

In [7]:
hyperparameter_results_dict = {}
for parameter in hyperparameters_df.columns[:-4]:
    print(parameter)
    hyperparameter_results_dict[parameter] = hyperparameters_df.groupby([parameter])[['test_mean_mae']].mean().copy()

max_depth
n_estimators
eta
min_child
subsample
gamma
lambda

In [8]:
 hyperparameter_results_dict['max_depth']

           test_mean_mae
max_depth
1               6.329576
2               6.407304
3               6.521071
4               6.658337
5               6.838671

In [9]:
 hyperparameter_results_dict['n_estimators']

              test_mean_mae
n_estimators
3                  6.447385
10                 6.651967

In [10]:
 hyperparameter_results_dict['eta']

       test_mean_mae
eta
0.001       6.310920
0.300       6.777431

In [11]:
 hyperparameter_results_dict['min_child']

           test_mean_mae
min_child
0               6.605455
100             6.438560

In [12]:
 hyperparameter_results_dict['subsample']

           test_mean_mae
subsample
1               6.547999

In [13]:
 hyperparameter_results_dict['gamma']

       test_mean_mae
gamma
0           6.532303
100         6.577898

In [14]:
 hyperparameter_results_dict['lambda']

        test_mean_mae
lambda
0            6.677115
100          6.414580

In [22]:
hyperparameters_df.head(20)

,max_depth,n_estimators,eta,min_child,subsample,gamma,lambda,train_mean_mae,train_std_mae,test_mean_mae,test_std_mae
99,5,10,0.001,100,1,0,0,6.4199,0.1969,6.3069,0.3405
39,5,10,0.001,0,1,0,100,6.4199,0.1969,6.3071,0.3410
79,5,10,0.001,0,1,100,100,6.4199,0.1969,6.3071,0.3410
59,5,10,0.001,0,1,100,0,6.4199,0.1969,6.3072,0.3404
19,5,10,0.001,0,1,0,0,6.4199,0.1969,6.3073,0.3404
119,5,10,0.001,100,1,0,100,6.4199,0.1969,6.3074,0.3409
98,4,10,0.001,100,1,0,0,6.4200,0.1969,6.3074,0.3410
78,4,10,0.001,0,1,100,100,6.4200,0.1969,6.3075,0.3412
38,4,10,0.001,0,1,0,100,6.4200,0.1969,6.3075,0.3412
118,4,10,0.001,100,1,0,100,6.4200,0.1969,6.3076,0.3412
58,4,10,0.001,0,1,100,0,6.4200,0.1969,6.3081,0.3410
18,4,10,0.001,0,1,0,0,6.4200,0.1969,6.3081,0.3410
117,3,10,0.001,100,1,0,100,6.4201,0.1969,6.3083,0.3411
37,3,10,0.001,0,1,0,100,6.4201,0.1969,6.3083,0.3412
77,3,10,0.001,0,1,100,100,6.4201,0.1969,6.3083,0.3412
97,3,10,0.001,100,1,0,0,6.4201,0.1969,6.3084,0.3412
57,3,10,0.001,0,1,100,0,6.4201,0.1969,6.3095,0.3410
17,3,10,0.001,0,1,0,0,6.4201,0.1969,6.3095,0.3410
36,2,10,0.001,0,1,0,100,6.4203,0.1969,6.3096,0.3417
76,2,10,0.001,0,1,100,100,6.4203,0.1969,6.3096,0.3417